# Makefile.in generated by automake 1.11.6 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011 Free Software
# Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.





am__make_dryrun = \
  { \
    am__dry=no; \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        echo 'am--echo: ; @echo "AM"  OK' | $(MAKE) -f - 2>/dev/null \
          | grep '^AM OK$$' >/dev/null || am__dry=yes;; \
      *) \
        for am__flg in $$MAKEFLAGS; do \
          case $$am__flg in \
            *=*|--*) ;; \
            *n*) am__dry=yes; break;; \
          esac; \
        done;; \
    esac; \
    test $$am__dry = yes; \
  }
pkgdatadir = $(datadir)/SampleApp
pkgincludedir = $(includedir)/SampleApp
pkglibdir = $(libdir)/SampleApp
pkglibexecdir = $(libexecdir)/SampleApp
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
bin_PROGRAMS = App$(EXEEXT)
subdir = .
DIST_COMMON = $(am__configure_deps) $(noinst_HEADERS) \
	$(srcdir)/Makefile.am $(srcdir)/Makefile.in \
	$(srcdir)/config.h.in $(top_srcdir)/configure config.guess \
	config.sub depcomp install-sh ltmain.sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am_App_OBJECTS = App-main.$(OBJEXT) App-ApplicationMgr.$(OBJEXT) \
	App-Language.$(OBJEXT) App-InterfaceListener.$(OBJEXT) \
	App-InterfacePolymorphic.$(OBJEXT) App-CMDRouterMgr.$(OBJEXT) \
	App-RouterController.$(OBJEXT) App-RouterInterface.$(OBJEXT) \
	App-RouterMgr.$(OBJEXT) App-RouterView.$(OBJEXT) \
	App-ControllerAbstract.$(OBJEXT) App-Util.$(OBJEXT) \
	App-TableAbstract.$(OBJEXT) App-CMDApplication.$(OBJEXT) \
	App-Database.$(OBJEXT) App-TableRowAbstract.$(OBJEXT) \
	App-BaseController.$(OBJEXT) App-MessageController.$(OBJEXT) \
	App-DefaultController.$(OBJEXT) App-ErrorController.$(OBJEXT) \
	App-Bootstrap.$(OBJEXT) App-ModelProblem.$(OBJEXT) \
	App-ModelProblems.$(OBJEXT) App-ModelSolutions.$(OBJEXT) \
	App-ControllerSolution.$(OBJEXT) \
	App-HelperOrderResultByWeight.$(OBJEXT)
App_OBJECTS = $(am_App_OBJECTS)
App_DEPENDENCIES =
App_LINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CXXLD) $(App_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(App_SOURCES)
DIST_SOURCES = $(App_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
HEADERS = $(noinst_HEADERS)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/jean/projects/rpcOgre/missing --run aclocal-1.11
AMTAR = $${TAR-tar}
AR = ar
AUTOCONF = ${SHELL} /home/jean/projects/rpcOgre/missing --run autoconf
AUTOHEADER = ${SHELL} /home/jean/projects/rpcOgre/missing --run autoheader
AUTOMAKE = ${SHELL} /home/jean/projects/rpcOgre/missing --run automake-1.11
AWK = mawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FGREP = /bin/grep -F
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/jean/projects/rpcOgre/missing --run makeinfo
MANIFEST_TOOL = :
MKDIR_P = /bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = SampleApp
PACKAGE_BUGREPORT = 
PACKAGE_NAME = 
PACKAGE_STRING = 
PACKAGE_TARNAME = 
PACKAGE_URL = 
PACKAGE_VERSION = 
PATH_SEPARATOR = :
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
STRIP = strip
VERSION = 0.1
abs_builddir = /home/jean/projects/rpcOgre
abs_srcdir = /home/jean/projects/rpcOgre
abs_top_builddir = /home/jean/projects/rpcOgre
abs_top_srcdir = /home/jean/projects/rpcOgre
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/jean/projects/rpcOgre/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
noinst_HEADERS = System/Db/TableAbstract.h System/Db/TableRowAbstract.h System/BootstrapAbstract.h  System/Db/Database.h Application/Bootstrap.h Application/ErrorController.h System/Object/Util.h Application/ModelSolutions.h Application/ControllerSolution.h Application/HelperOrderResultByWeight.h Application/ModelProblem.h
App_CPPFLAGS = -I$(top_srcdir) -lsqlite3
App_SOURCES = main.cpp   					System/ApplicationMgr.cpp System/Language.cpp System/DesignPattern/InterfaceListener.cpp System/DesignPattern/InterfacePolymorphic.cpp System/Router/CMDRouterMgr.cpp System/Router/RouterController.cpp System/Router/RouterInterface.cpp System/Router/RouterMgr.cpp System/Router/RouterView.cpp System/ControllerAbstract.cpp  System/Object/Util.cpp System/Db/TableAbstract.cpp System/CMDApplication.cpp System/Db/Database.cpp System/Db/TableRowAbstract.cpp 								Application/BaseController.cpp Application/MessageController.cpp Application/DefaultController.cpp  Application/ErrorController.cpp  Application/Bootstrap.cpp Application/ModelProblem.cpp Application/ModelProblems.cpp Application/ModelSolutions.cpp Application/ControllerSolution.cpp Application/HelperOrderResultByWeight.cpp
App_CXXFLAGS = $(OGRE_CFLAGS) $(OIS_CFLAGS) -lsqlite3
App_LDADD = $(OGRE_LIBS) $(OIS_LIBS) -lsqlite3
EXTRA_DIST = bootstrap
AUTOMAKE_OPTIONS = foreign
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .cpp .lo .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@if test ! -f $@; then rm -f stamp-h1; else :; fi
	@if test ! -f $@; then $(MAKE) $(AM_MAKEFLAGS) stamp-h1; else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p || test -f $$p1; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
App$(EXEEXT): $(App_OBJECTS) $(App_DEPENDENCIES) $(EXTRA_App_DEPENDENCIES) 
	@rm -f App$(EXEEXT)
	$(App_LINK) $(App_OBJECTS) $(App_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/App-ApplicationMgr.Po
include ./$(DEPDIR)/App-BaseController.Po
include ./$(DEPDIR)/App-Bootstrap.Po
include ./$(DEPDIR)/App-CMDApplication.Po
include ./$(DEPDIR)/App-CMDRouterMgr.Po
include ./$(DEPDIR)/App-ControllerAbstract.Po
include ./$(DEPDIR)/App-ControllerSolution.Po
include ./$(DEPDIR)/App-Database.Po
include ./$(DEPDIR)/App-DefaultController.Po
include ./$(DEPDIR)/App-ErrorController.Po
include ./$(DEPDIR)/App-HelperOrderResultByWeight.Po
include ./$(DEPDIR)/App-InterfaceListener.Po
include ./$(DEPDIR)/App-InterfacePolymorphic.Po
include ./$(DEPDIR)/App-Language.Po
include ./$(DEPDIR)/App-MessageController.Po
include ./$(DEPDIR)/App-ModelProblem.Po
include ./$(DEPDIR)/App-ModelProblems.Po
include ./$(DEPDIR)/App-ModelSolutions.Po
include ./$(DEPDIR)/App-RouterController.Po
include ./$(DEPDIR)/App-RouterInterface.Po
include ./$(DEPDIR)/App-RouterMgr.Po
include ./$(DEPDIR)/App-RouterView.Po
include ./$(DEPDIR)/App-TableAbstract.Po
include ./$(DEPDIR)/App-TableRowAbstract.Po
include ./$(DEPDIR)/App-Util.Po
include ./$(DEPDIR)/App-main.Po

.cpp.o:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cpp.lo:
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LTCXXCOMPILE) -c -o $@ $<

App-main.o: main.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-main.o -MD -MP -MF $(DEPDIR)/App-main.Tpo -c -o App-main.o `test -f 'main.cpp' || echo '$(srcdir)/'`main.cpp
	$(am__mv) $(DEPDIR)/App-main.Tpo $(DEPDIR)/App-main.Po
#	source='main.cpp' object='App-main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-main.o `test -f 'main.cpp' || echo '$(srcdir)/'`main.cpp

App-main.obj: main.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-main.obj -MD -MP -MF $(DEPDIR)/App-main.Tpo -c -o App-main.obj `if test -f 'main.cpp'; then $(CYGPATH_W) 'main.cpp'; else $(CYGPATH_W) '$(srcdir)/main.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-main.Tpo $(DEPDIR)/App-main.Po
#	source='main.cpp' object='App-main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-main.obj `if test -f 'main.cpp'; then $(CYGPATH_W) 'main.cpp'; else $(CYGPATH_W) '$(srcdir)/main.cpp'; fi`

App-ApplicationMgr.o: System/ApplicationMgr.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-ApplicationMgr.o -MD -MP -MF $(DEPDIR)/App-ApplicationMgr.Tpo -c -o App-ApplicationMgr.o `test -f 'System/ApplicationMgr.cpp' || echo '$(srcdir)/'`System/ApplicationMgr.cpp
	$(am__mv) $(DEPDIR)/App-ApplicationMgr.Tpo $(DEPDIR)/App-ApplicationMgr.Po
#	source='System/ApplicationMgr.cpp' object='App-ApplicationMgr.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-ApplicationMgr.o `test -f 'System/ApplicationMgr.cpp' || echo '$(srcdir)/'`System/ApplicationMgr.cpp

App-ApplicationMgr.obj: System/ApplicationMgr.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-ApplicationMgr.obj -MD -MP -MF $(DEPDIR)/App-ApplicationMgr.Tpo -c -o App-ApplicationMgr.obj `if test -f 'System/ApplicationMgr.cpp'; then $(CYGPATH_W) 'System/ApplicationMgr.cpp'; else $(CYGPATH_W) '$(srcdir)/System/ApplicationMgr.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-ApplicationMgr.Tpo $(DEPDIR)/App-ApplicationMgr.Po
#	source='System/ApplicationMgr.cpp' object='App-ApplicationMgr.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-ApplicationMgr.obj `if test -f 'System/ApplicationMgr.cpp'; then $(CYGPATH_W) 'System/ApplicationMgr.cpp'; else $(CYGPATH_W) '$(srcdir)/System/ApplicationMgr.cpp'; fi`

App-Language.o: System/Language.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-Language.o -MD -MP -MF $(DEPDIR)/App-Language.Tpo -c -o App-Language.o `test -f 'System/Language.cpp' || echo '$(srcdir)/'`System/Language.cpp
	$(am__mv) $(DEPDIR)/App-Language.Tpo $(DEPDIR)/App-Language.Po
#	source='System/Language.cpp' object='App-Language.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-Language.o `test -f 'System/Language.cpp' || echo '$(srcdir)/'`System/Language.cpp

App-Language.obj: System/Language.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-Language.obj -MD -MP -MF $(DEPDIR)/App-Language.Tpo -c -o App-Language.obj `if test -f 'System/Language.cpp'; then $(CYGPATH_W) 'System/Language.cpp'; else $(CYGPATH_W) '$(srcdir)/System/Language.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-Language.Tpo $(DEPDIR)/App-Language.Po
#	source='System/Language.cpp' object='App-Language.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-Language.obj `if test -f 'System/Language.cpp'; then $(CYGPATH_W) 'System/Language.cpp'; else $(CYGPATH_W) '$(srcdir)/System/Language.cpp'; fi`

App-InterfaceListener.o: System/DesignPattern/InterfaceListener.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-InterfaceListener.o -MD -MP -MF $(DEPDIR)/App-InterfaceListener.Tpo -c -o App-InterfaceListener.o `test -f 'System/DesignPattern/InterfaceListener.cpp' || echo '$(srcdir)/'`System/DesignPattern/InterfaceListener.cpp
	$(am__mv) $(DEPDIR)/App-InterfaceListener.Tpo $(DEPDIR)/App-InterfaceListener.Po
#	source='System/DesignPattern/InterfaceListener.cpp' object='App-InterfaceListener.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-InterfaceListener.o `test -f 'System/DesignPattern/InterfaceListener.cpp' || echo '$(srcdir)/'`System/DesignPattern/InterfaceListener.cpp

App-InterfaceListener.obj: System/DesignPattern/InterfaceListener.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-InterfaceListener.obj -MD -MP -MF $(DEPDIR)/App-InterfaceListener.Tpo -c -o App-InterfaceListener.obj `if test -f 'System/DesignPattern/InterfaceListener.cpp'; then $(CYGPATH_W) 'System/DesignPattern/InterfaceListener.cpp'; else $(CYGPATH_W) '$(srcdir)/System/DesignPattern/InterfaceListener.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-InterfaceListener.Tpo $(DEPDIR)/App-InterfaceListener.Po
#	source='System/DesignPattern/InterfaceListener.cpp' object='App-InterfaceListener.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-InterfaceListener.obj `if test -f 'System/DesignPattern/InterfaceListener.cpp'; then $(CYGPATH_W) 'System/DesignPattern/InterfaceListener.cpp'; else $(CYGPATH_W) '$(srcdir)/System/DesignPattern/InterfaceListener.cpp'; fi`

App-InterfacePolymorphic.o: System/DesignPattern/InterfacePolymorphic.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-InterfacePolymorphic.o -MD -MP -MF $(DEPDIR)/App-InterfacePolymorphic.Tpo -c -o App-InterfacePolymorphic.o `test -f 'System/DesignPattern/InterfacePolymorphic.cpp' || echo '$(srcdir)/'`System/DesignPattern/InterfacePolymorphic.cpp
	$(am__mv) $(DEPDIR)/App-InterfacePolymorphic.Tpo $(DEPDIR)/App-InterfacePolymorphic.Po
#	source='System/DesignPattern/InterfacePolymorphic.cpp' object='App-InterfacePolymorphic.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-InterfacePolymorphic.o `test -f 'System/DesignPattern/InterfacePolymorphic.cpp' || echo '$(srcdir)/'`System/DesignPattern/InterfacePolymorphic.cpp

App-InterfacePolymorphic.obj: System/DesignPattern/InterfacePolymorphic.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-InterfacePolymorphic.obj -MD -MP -MF $(DEPDIR)/App-InterfacePolymorphic.Tpo -c -o App-InterfacePolymorphic.obj `if test -f 'System/DesignPattern/InterfacePolymorphic.cpp'; then $(CYGPATH_W) 'System/DesignPattern/InterfacePolymorphic.cpp'; else $(CYGPATH_W) '$(srcdir)/System/DesignPattern/InterfacePolymorphic.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-InterfacePolymorphic.Tpo $(DEPDIR)/App-InterfacePolymorphic.Po
#	source='System/DesignPattern/InterfacePolymorphic.cpp' object='App-InterfacePolymorphic.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-InterfacePolymorphic.obj `if test -f 'System/DesignPattern/InterfacePolymorphic.cpp'; then $(CYGPATH_W) 'System/DesignPattern/InterfacePolymorphic.cpp'; else $(CYGPATH_W) '$(srcdir)/System/DesignPattern/InterfacePolymorphic.cpp'; fi`

App-CMDRouterMgr.o: System/Router/CMDRouterMgr.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-CMDRouterMgr.o -MD -MP -MF $(DEPDIR)/App-CMDRouterMgr.Tpo -c -o App-CMDRouterMgr.o `test -f 'System/Router/CMDRouterMgr.cpp' || echo '$(srcdir)/'`System/Router/CMDRouterMgr.cpp
	$(am__mv) $(DEPDIR)/App-CMDRouterMgr.Tpo $(DEPDIR)/App-CMDRouterMgr.Po
#	source='System/Router/CMDRouterMgr.cpp' object='App-CMDRouterMgr.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-CMDRouterMgr.o `test -f 'System/Router/CMDRouterMgr.cpp' || echo '$(srcdir)/'`System/Router/CMDRouterMgr.cpp

App-CMDRouterMgr.obj: System/Router/CMDRouterMgr.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-CMDRouterMgr.obj -MD -MP -MF $(DEPDIR)/App-CMDRouterMgr.Tpo -c -o App-CMDRouterMgr.obj `if test -f 'System/Router/CMDRouterMgr.cpp'; then $(CYGPATH_W) 'System/Router/CMDRouterMgr.cpp'; else $(CYGPATH_W) '$(srcdir)/System/Router/CMDRouterMgr.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-CMDRouterMgr.Tpo $(DEPDIR)/App-CMDRouterMgr.Po
#	source='System/Router/CMDRouterMgr.cpp' object='App-CMDRouterMgr.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-CMDRouterMgr.obj `if test -f 'System/Router/CMDRouterMgr.cpp'; then $(CYGPATH_W) 'System/Router/CMDRouterMgr.cpp'; else $(CYGPATH_W) '$(srcdir)/System/Router/CMDRouterMgr.cpp'; fi`

App-RouterController.o: System/Router/RouterController.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-RouterController.o -MD -MP -MF $(DEPDIR)/App-RouterController.Tpo -c -o App-RouterController.o `test -f 'System/Router/RouterController.cpp' || echo '$(srcdir)/'`System/Router/RouterController.cpp
	$(am__mv) $(DEPDIR)/App-RouterController.Tpo $(DEPDIR)/App-RouterController.Po
#	source='System/Router/RouterController.cpp' object='App-RouterController.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-RouterController.o `test -f 'System/Router/RouterController.cpp' || echo '$(srcdir)/'`System/Router/RouterController.cpp

App-RouterController.obj: System/Router/RouterController.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-RouterController.obj -MD -MP -MF $(DEPDIR)/App-RouterController.Tpo -c -o App-RouterController.obj `if test -f 'System/Router/RouterController.cpp'; then $(CYGPATH_W) 'System/Router/RouterController.cpp'; else $(CYGPATH_W) '$(srcdir)/System/Router/RouterController.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-RouterController.Tpo $(DEPDIR)/App-RouterController.Po
#	source='System/Router/RouterController.cpp' object='App-RouterController.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-RouterController.obj `if test -f 'System/Router/RouterController.cpp'; then $(CYGPATH_W) 'System/Router/RouterController.cpp'; else $(CYGPATH_W) '$(srcdir)/System/Router/RouterController.cpp'; fi`

App-RouterInterface.o: System/Router/RouterInterface.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-RouterInterface.o -MD -MP -MF $(DEPDIR)/App-RouterInterface.Tpo -c -o App-RouterInterface.o `test -f 'System/Router/RouterInterface.cpp' || echo '$(srcdir)/'`System/Router/RouterInterface.cpp
	$(am__mv) $(DEPDIR)/App-RouterInterface.Tpo $(DEPDIR)/App-RouterInterface.Po
#	source='System/Router/RouterInterface.cpp' object='App-RouterInterface.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-RouterInterface.o `test -f 'System/Router/RouterInterface.cpp' || echo '$(srcdir)/'`System/Router/RouterInterface.cpp

App-RouterInterface.obj: System/Router/RouterInterface.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-RouterInterface.obj -MD -MP -MF $(DEPDIR)/App-RouterInterface.Tpo -c -o App-RouterInterface.obj `if test -f 'System/Router/RouterInterface.cpp'; then $(CYGPATH_W) 'System/Router/RouterInterface.cpp'; else $(CYGPATH_W) '$(srcdir)/System/Router/RouterInterface.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-RouterInterface.Tpo $(DEPDIR)/App-RouterInterface.Po
#	source='System/Router/RouterInterface.cpp' object='App-RouterInterface.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-RouterInterface.obj `if test -f 'System/Router/RouterInterface.cpp'; then $(CYGPATH_W) 'System/Router/RouterInterface.cpp'; else $(CYGPATH_W) '$(srcdir)/System/Router/RouterInterface.cpp'; fi`

App-RouterMgr.o: System/Router/RouterMgr.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-RouterMgr.o -MD -MP -MF $(DEPDIR)/App-RouterMgr.Tpo -c -o App-RouterMgr.o `test -f 'System/Router/RouterMgr.cpp' || echo '$(srcdir)/'`System/Router/RouterMgr.cpp
	$(am__mv) $(DEPDIR)/App-RouterMgr.Tpo $(DEPDIR)/App-RouterMgr.Po
#	source='System/Router/RouterMgr.cpp' object='App-RouterMgr.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-RouterMgr.o `test -f 'System/Router/RouterMgr.cpp' || echo '$(srcdir)/'`System/Router/RouterMgr.cpp

App-RouterMgr.obj: System/Router/RouterMgr.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-RouterMgr.obj -MD -MP -MF $(DEPDIR)/App-RouterMgr.Tpo -c -o App-RouterMgr.obj `if test -f 'System/Router/RouterMgr.cpp'; then $(CYGPATH_W) 'System/Router/RouterMgr.cpp'; else $(CYGPATH_W) '$(srcdir)/System/Router/RouterMgr.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-RouterMgr.Tpo $(DEPDIR)/App-RouterMgr.Po
#	source='System/Router/RouterMgr.cpp' object='App-RouterMgr.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-RouterMgr.obj `if test -f 'System/Router/RouterMgr.cpp'; then $(CYGPATH_W) 'System/Router/RouterMgr.cpp'; else $(CYGPATH_W) '$(srcdir)/System/Router/RouterMgr.cpp'; fi`

App-RouterView.o: System/Router/RouterView.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-RouterView.o -MD -MP -MF $(DEPDIR)/App-RouterView.Tpo -c -o App-RouterView.o `test -f 'System/Router/RouterView.cpp' || echo '$(srcdir)/'`System/Router/RouterView.cpp
	$(am__mv) $(DEPDIR)/App-RouterView.Tpo $(DEPDIR)/App-RouterView.Po
#	source='System/Router/RouterView.cpp' object='App-RouterView.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-RouterView.o `test -f 'System/Router/RouterView.cpp' || echo '$(srcdir)/'`System/Router/RouterView.cpp

App-RouterView.obj: System/Router/RouterView.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-RouterView.obj -MD -MP -MF $(DEPDIR)/App-RouterView.Tpo -c -o App-RouterView.obj `if test -f 'System/Router/RouterView.cpp'; then $(CYGPATH_W) 'System/Router/RouterView.cpp'; else $(CYGPATH_W) '$(srcdir)/System/Router/RouterView.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-RouterView.Tpo $(DEPDIR)/App-RouterView.Po
#	source='System/Router/RouterView.cpp' object='App-RouterView.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-RouterView.obj `if test -f 'System/Router/RouterView.cpp'; then $(CYGPATH_W) 'System/Router/RouterView.cpp'; else $(CYGPATH_W) '$(srcdir)/System/Router/RouterView.cpp'; fi`

App-ControllerAbstract.o: System/ControllerAbstract.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-ControllerAbstract.o -MD -MP -MF $(DEPDIR)/App-ControllerAbstract.Tpo -c -o App-ControllerAbstract.o `test -f 'System/ControllerAbstract.cpp' || echo '$(srcdir)/'`System/ControllerAbstract.cpp
	$(am__mv) $(DEPDIR)/App-ControllerAbstract.Tpo $(DEPDIR)/App-ControllerAbstract.Po
#	source='System/ControllerAbstract.cpp' object='App-ControllerAbstract.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-ControllerAbstract.o `test -f 'System/ControllerAbstract.cpp' || echo '$(srcdir)/'`System/ControllerAbstract.cpp

App-ControllerAbstract.obj: System/ControllerAbstract.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-ControllerAbstract.obj -MD -MP -MF $(DEPDIR)/App-ControllerAbstract.Tpo -c -o App-ControllerAbstract.obj `if test -f 'System/ControllerAbstract.cpp'; then $(CYGPATH_W) 'System/ControllerAbstract.cpp'; else $(CYGPATH_W) '$(srcdir)/System/ControllerAbstract.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-ControllerAbstract.Tpo $(DEPDIR)/App-ControllerAbstract.Po
#	source='System/ControllerAbstract.cpp' object='App-ControllerAbstract.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-ControllerAbstract.obj `if test -f 'System/ControllerAbstract.cpp'; then $(CYGPATH_W) 'System/ControllerAbstract.cpp'; else $(CYGPATH_W) '$(srcdir)/System/ControllerAbstract.cpp'; fi`

App-Util.o: System/Object/Util.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-Util.o -MD -MP -MF $(DEPDIR)/App-Util.Tpo -c -o App-Util.o `test -f 'System/Object/Util.cpp' || echo '$(srcdir)/'`System/Object/Util.cpp
	$(am__mv) $(DEPDIR)/App-Util.Tpo $(DEPDIR)/App-Util.Po
#	source='System/Object/Util.cpp' object='App-Util.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-Util.o `test -f 'System/Object/Util.cpp' || echo '$(srcdir)/'`System/Object/Util.cpp

App-Util.obj: System/Object/Util.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-Util.obj -MD -MP -MF $(DEPDIR)/App-Util.Tpo -c -o App-Util.obj `if test -f 'System/Object/Util.cpp'; then $(CYGPATH_W) 'System/Object/Util.cpp'; else $(CYGPATH_W) '$(srcdir)/System/Object/Util.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-Util.Tpo $(DEPDIR)/App-Util.Po
#	source='System/Object/Util.cpp' object='App-Util.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-Util.obj `if test -f 'System/Object/Util.cpp'; then $(CYGPATH_W) 'System/Object/Util.cpp'; else $(CYGPATH_W) '$(srcdir)/System/Object/Util.cpp'; fi`

App-TableAbstract.o: System/Db/TableAbstract.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-TableAbstract.o -MD -MP -MF $(DEPDIR)/App-TableAbstract.Tpo -c -o App-TableAbstract.o `test -f 'System/Db/TableAbstract.cpp' || echo '$(srcdir)/'`System/Db/TableAbstract.cpp
	$(am__mv) $(DEPDIR)/App-TableAbstract.Tpo $(DEPDIR)/App-TableAbstract.Po
#	source='System/Db/TableAbstract.cpp' object='App-TableAbstract.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-TableAbstract.o `test -f 'System/Db/TableAbstract.cpp' || echo '$(srcdir)/'`System/Db/TableAbstract.cpp

App-TableAbstract.obj: System/Db/TableAbstract.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-TableAbstract.obj -MD -MP -MF $(DEPDIR)/App-TableAbstract.Tpo -c -o App-TableAbstract.obj `if test -f 'System/Db/TableAbstract.cpp'; then $(CYGPATH_W) 'System/Db/TableAbstract.cpp'; else $(CYGPATH_W) '$(srcdir)/System/Db/TableAbstract.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-TableAbstract.Tpo $(DEPDIR)/App-TableAbstract.Po
#	source='System/Db/TableAbstract.cpp' object='App-TableAbstract.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-TableAbstract.obj `if test -f 'System/Db/TableAbstract.cpp'; then $(CYGPATH_W) 'System/Db/TableAbstract.cpp'; else $(CYGPATH_W) '$(srcdir)/System/Db/TableAbstract.cpp'; fi`

App-CMDApplication.o: System/CMDApplication.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-CMDApplication.o -MD -MP -MF $(DEPDIR)/App-CMDApplication.Tpo -c -o App-CMDApplication.o `test -f 'System/CMDApplication.cpp' || echo '$(srcdir)/'`System/CMDApplication.cpp
	$(am__mv) $(DEPDIR)/App-CMDApplication.Tpo $(DEPDIR)/App-CMDApplication.Po
#	source='System/CMDApplication.cpp' object='App-CMDApplication.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-CMDApplication.o `test -f 'System/CMDApplication.cpp' || echo '$(srcdir)/'`System/CMDApplication.cpp

App-CMDApplication.obj: System/CMDApplication.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-CMDApplication.obj -MD -MP -MF $(DEPDIR)/App-CMDApplication.Tpo -c -o App-CMDApplication.obj `if test -f 'System/CMDApplication.cpp'; then $(CYGPATH_W) 'System/CMDApplication.cpp'; else $(CYGPATH_W) '$(srcdir)/System/CMDApplication.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-CMDApplication.Tpo $(DEPDIR)/App-CMDApplication.Po
#	source='System/CMDApplication.cpp' object='App-CMDApplication.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-CMDApplication.obj `if test -f 'System/CMDApplication.cpp'; then $(CYGPATH_W) 'System/CMDApplication.cpp'; else $(CYGPATH_W) '$(srcdir)/System/CMDApplication.cpp'; fi`

App-Database.o: System/Db/Database.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-Database.o -MD -MP -MF $(DEPDIR)/App-Database.Tpo -c -o App-Database.o `test -f 'System/Db/Database.cpp' || echo '$(srcdir)/'`System/Db/Database.cpp
	$(am__mv) $(DEPDIR)/App-Database.Tpo $(DEPDIR)/App-Database.Po
#	source='System/Db/Database.cpp' object='App-Database.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-Database.o `test -f 'System/Db/Database.cpp' || echo '$(srcdir)/'`System/Db/Database.cpp

App-Database.obj: System/Db/Database.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-Database.obj -MD -MP -MF $(DEPDIR)/App-Database.Tpo -c -o App-Database.obj `if test -f 'System/Db/Database.cpp'; then $(CYGPATH_W) 'System/Db/Database.cpp'; else $(CYGPATH_W) '$(srcdir)/System/Db/Database.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-Database.Tpo $(DEPDIR)/App-Database.Po
#	source='System/Db/Database.cpp' object='App-Database.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-Database.obj `if test -f 'System/Db/Database.cpp'; then $(CYGPATH_W) 'System/Db/Database.cpp'; else $(CYGPATH_W) '$(srcdir)/System/Db/Database.cpp'; fi`

App-TableRowAbstract.o: System/Db/TableRowAbstract.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-TableRowAbstract.o -MD -MP -MF $(DEPDIR)/App-TableRowAbstract.Tpo -c -o App-TableRowAbstract.o `test -f 'System/Db/TableRowAbstract.cpp' || echo '$(srcdir)/'`System/Db/TableRowAbstract.cpp
	$(am__mv) $(DEPDIR)/App-TableRowAbstract.Tpo $(DEPDIR)/App-TableRowAbstract.Po
#	source='System/Db/TableRowAbstract.cpp' object='App-TableRowAbstract.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-TableRowAbstract.o `test -f 'System/Db/TableRowAbstract.cpp' || echo '$(srcdir)/'`System/Db/TableRowAbstract.cpp

App-TableRowAbstract.obj: System/Db/TableRowAbstract.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-TableRowAbstract.obj -MD -MP -MF $(DEPDIR)/App-TableRowAbstract.Tpo -c -o App-TableRowAbstract.obj `if test -f 'System/Db/TableRowAbstract.cpp'; then $(CYGPATH_W) 'System/Db/TableRowAbstract.cpp'; else $(CYGPATH_W) '$(srcdir)/System/Db/TableRowAbstract.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-TableRowAbstract.Tpo $(DEPDIR)/App-TableRowAbstract.Po
#	source='System/Db/TableRowAbstract.cpp' object='App-TableRowAbstract.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-TableRowAbstract.obj `if test -f 'System/Db/TableRowAbstract.cpp'; then $(CYGPATH_W) 'System/Db/TableRowAbstract.cpp'; else $(CYGPATH_W) '$(srcdir)/System/Db/TableRowAbstract.cpp'; fi`

App-BaseController.o: Application/BaseController.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-BaseController.o -MD -MP -MF $(DEPDIR)/App-BaseController.Tpo -c -o App-BaseController.o `test -f 'Application/BaseController.cpp' || echo '$(srcdir)/'`Application/BaseController.cpp
	$(am__mv) $(DEPDIR)/App-BaseController.Tpo $(DEPDIR)/App-BaseController.Po
#	source='Application/BaseController.cpp' object='App-BaseController.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-BaseController.o `test -f 'Application/BaseController.cpp' || echo '$(srcdir)/'`Application/BaseController.cpp

App-BaseController.obj: Application/BaseController.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-BaseController.obj -MD -MP -MF $(DEPDIR)/App-BaseController.Tpo -c -o App-BaseController.obj `if test -f 'Application/BaseController.cpp'; then $(CYGPATH_W) 'Application/BaseController.cpp'; else $(CYGPATH_W) '$(srcdir)/Application/BaseController.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-BaseController.Tpo $(DEPDIR)/App-BaseController.Po
#	source='Application/BaseController.cpp' object='App-BaseController.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-BaseController.obj `if test -f 'Application/BaseController.cpp'; then $(CYGPATH_W) 'Application/BaseController.cpp'; else $(CYGPATH_W) '$(srcdir)/Application/BaseController.cpp'; fi`

App-MessageController.o: Application/MessageController.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-MessageController.o -MD -MP -MF $(DEPDIR)/App-MessageController.Tpo -c -o App-MessageController.o `test -f 'Application/MessageController.cpp' || echo '$(srcdir)/'`Application/MessageController.cpp
	$(am__mv) $(DEPDIR)/App-MessageController.Tpo $(DEPDIR)/App-MessageController.Po
#	source='Application/MessageController.cpp' object='App-MessageController.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-MessageController.o `test -f 'Application/MessageController.cpp' || echo '$(srcdir)/'`Application/MessageController.cpp

App-MessageController.obj: Application/MessageController.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-MessageController.obj -MD -MP -MF $(DEPDIR)/App-MessageController.Tpo -c -o App-MessageController.obj `if test -f 'Application/MessageController.cpp'; then $(CYGPATH_W) 'Application/MessageController.cpp'; else $(CYGPATH_W) '$(srcdir)/Application/MessageController.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-MessageController.Tpo $(DEPDIR)/App-MessageController.Po
#	source='Application/MessageController.cpp' object='App-MessageController.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-MessageController.obj `if test -f 'Application/MessageController.cpp'; then $(CYGPATH_W) 'Application/MessageController.cpp'; else $(CYGPATH_W) '$(srcdir)/Application/MessageController.cpp'; fi`

App-DefaultController.o: Application/DefaultController.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-DefaultController.o -MD -MP -MF $(DEPDIR)/App-DefaultController.Tpo -c -o App-DefaultController.o `test -f 'Application/DefaultController.cpp' || echo '$(srcdir)/'`Application/DefaultController.cpp
	$(am__mv) $(DEPDIR)/App-DefaultController.Tpo $(DEPDIR)/App-DefaultController.Po
#	source='Application/DefaultController.cpp' object='App-DefaultController.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-DefaultController.o `test -f 'Application/DefaultController.cpp' || echo '$(srcdir)/'`Application/DefaultController.cpp

App-DefaultController.obj: Application/DefaultController.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-DefaultController.obj -MD -MP -MF $(DEPDIR)/App-DefaultController.Tpo -c -o App-DefaultController.obj `if test -f 'Application/DefaultController.cpp'; then $(CYGPATH_W) 'Application/DefaultController.cpp'; else $(CYGPATH_W) '$(srcdir)/Application/DefaultController.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-DefaultController.Tpo $(DEPDIR)/App-DefaultController.Po
#	source='Application/DefaultController.cpp' object='App-DefaultController.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-DefaultController.obj `if test -f 'Application/DefaultController.cpp'; then $(CYGPATH_W) 'Application/DefaultController.cpp'; else $(CYGPATH_W) '$(srcdir)/Application/DefaultController.cpp'; fi`

App-ErrorController.o: Application/ErrorController.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-ErrorController.o -MD -MP -MF $(DEPDIR)/App-ErrorController.Tpo -c -o App-ErrorController.o `test -f 'Application/ErrorController.cpp' || echo '$(srcdir)/'`Application/ErrorController.cpp
	$(am__mv) $(DEPDIR)/App-ErrorController.Tpo $(DEPDIR)/App-ErrorController.Po
#	source='Application/ErrorController.cpp' object='App-ErrorController.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-ErrorController.o `test -f 'Application/ErrorController.cpp' || echo '$(srcdir)/'`Application/ErrorController.cpp

App-ErrorController.obj: Application/ErrorController.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-ErrorController.obj -MD -MP -MF $(DEPDIR)/App-ErrorController.Tpo -c -o App-ErrorController.obj `if test -f 'Application/ErrorController.cpp'; then $(CYGPATH_W) 'Application/ErrorController.cpp'; else $(CYGPATH_W) '$(srcdir)/Application/ErrorController.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-ErrorController.Tpo $(DEPDIR)/App-ErrorController.Po
#	source='Application/ErrorController.cpp' object='App-ErrorController.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-ErrorController.obj `if test -f 'Application/ErrorController.cpp'; then $(CYGPATH_W) 'Application/ErrorController.cpp'; else $(CYGPATH_W) '$(srcdir)/Application/ErrorController.cpp'; fi`

App-Bootstrap.o: Application/Bootstrap.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-Bootstrap.o -MD -MP -MF $(DEPDIR)/App-Bootstrap.Tpo -c -o App-Bootstrap.o `test -f 'Application/Bootstrap.cpp' || echo '$(srcdir)/'`Application/Bootstrap.cpp
	$(am__mv) $(DEPDIR)/App-Bootstrap.Tpo $(DEPDIR)/App-Bootstrap.Po
#	source='Application/Bootstrap.cpp' object='App-Bootstrap.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-Bootstrap.o `test -f 'Application/Bootstrap.cpp' || echo '$(srcdir)/'`Application/Bootstrap.cpp

App-Bootstrap.obj: Application/Bootstrap.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-Bootstrap.obj -MD -MP -MF $(DEPDIR)/App-Bootstrap.Tpo -c -o App-Bootstrap.obj `if test -f 'Application/Bootstrap.cpp'; then $(CYGPATH_W) 'Application/Bootstrap.cpp'; else $(CYGPATH_W) '$(srcdir)/Application/Bootstrap.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-Bootstrap.Tpo $(DEPDIR)/App-Bootstrap.Po
#	source='Application/Bootstrap.cpp' object='App-Bootstrap.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-Bootstrap.obj `if test -f 'Application/Bootstrap.cpp'; then $(CYGPATH_W) 'Application/Bootstrap.cpp'; else $(CYGPATH_W) '$(srcdir)/Application/Bootstrap.cpp'; fi`

App-ModelProblem.o: Application/ModelProblem.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-ModelProblem.o -MD -MP -MF $(DEPDIR)/App-ModelProblem.Tpo -c -o App-ModelProblem.o `test -f 'Application/ModelProblem.cpp' || echo '$(srcdir)/'`Application/ModelProblem.cpp
	$(am__mv) $(DEPDIR)/App-ModelProblem.Tpo $(DEPDIR)/App-ModelProblem.Po
#	source='Application/ModelProblem.cpp' object='App-ModelProblem.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-ModelProblem.o `test -f 'Application/ModelProblem.cpp' || echo '$(srcdir)/'`Application/ModelProblem.cpp

App-ModelProblem.obj: Application/ModelProblem.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-ModelProblem.obj -MD -MP -MF $(DEPDIR)/App-ModelProblem.Tpo -c -o App-ModelProblem.obj `if test -f 'Application/ModelProblem.cpp'; then $(CYGPATH_W) 'Application/ModelProblem.cpp'; else $(CYGPATH_W) '$(srcdir)/Application/ModelProblem.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-ModelProblem.Tpo $(DEPDIR)/App-ModelProblem.Po
#	source='Application/ModelProblem.cpp' object='App-ModelProblem.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-ModelProblem.obj `if test -f 'Application/ModelProblem.cpp'; then $(CYGPATH_W) 'Application/ModelProblem.cpp'; else $(CYGPATH_W) '$(srcdir)/Application/ModelProblem.cpp'; fi`

App-ModelProblems.o: Application/ModelProblems.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-ModelProblems.o -MD -MP -MF $(DEPDIR)/App-ModelProblems.Tpo -c -o App-ModelProblems.o `test -f 'Application/ModelProblems.cpp' || echo '$(srcdir)/'`Application/ModelProblems.cpp
	$(am__mv) $(DEPDIR)/App-ModelProblems.Tpo $(DEPDIR)/App-ModelProblems.Po
#	source='Application/ModelProblems.cpp' object='App-ModelProblems.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-ModelProblems.o `test -f 'Application/ModelProblems.cpp' || echo '$(srcdir)/'`Application/ModelProblems.cpp

App-ModelProblems.obj: Application/ModelProblems.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-ModelProblems.obj -MD -MP -MF $(DEPDIR)/App-ModelProblems.Tpo -c -o App-ModelProblems.obj `if test -f 'Application/ModelProblems.cpp'; then $(CYGPATH_W) 'Application/ModelProblems.cpp'; else $(CYGPATH_W) '$(srcdir)/Application/ModelProblems.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-ModelProblems.Tpo $(DEPDIR)/App-ModelProblems.Po
#	source='Application/ModelProblems.cpp' object='App-ModelProblems.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-ModelProblems.obj `if test -f 'Application/ModelProblems.cpp'; then $(CYGPATH_W) 'Application/ModelProblems.cpp'; else $(CYGPATH_W) '$(srcdir)/Application/ModelProblems.cpp'; fi`

App-ModelSolutions.o: Application/ModelSolutions.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-ModelSolutions.o -MD -MP -MF $(DEPDIR)/App-ModelSolutions.Tpo -c -o App-ModelSolutions.o `test -f 'Application/ModelSolutions.cpp' || echo '$(srcdir)/'`Application/ModelSolutions.cpp
	$(am__mv) $(DEPDIR)/App-ModelSolutions.Tpo $(DEPDIR)/App-ModelSolutions.Po
#	source='Application/ModelSolutions.cpp' object='App-ModelSolutions.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-ModelSolutions.o `test -f 'Application/ModelSolutions.cpp' || echo '$(srcdir)/'`Application/ModelSolutions.cpp

App-ModelSolutions.obj: Application/ModelSolutions.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-ModelSolutions.obj -MD -MP -MF $(DEPDIR)/App-ModelSolutions.Tpo -c -o App-ModelSolutions.obj `if test -f 'Application/ModelSolutions.cpp'; then $(CYGPATH_W) 'Application/ModelSolutions.cpp'; else $(CYGPATH_W) '$(srcdir)/Application/ModelSolutions.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-ModelSolutions.Tpo $(DEPDIR)/App-ModelSolutions.Po
#	source='Application/ModelSolutions.cpp' object='App-ModelSolutions.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-ModelSolutions.obj `if test -f 'Application/ModelSolutions.cpp'; then $(CYGPATH_W) 'Application/ModelSolutions.cpp'; else $(CYGPATH_W) '$(srcdir)/Application/ModelSolutions.cpp'; fi`

App-ControllerSolution.o: Application/ControllerSolution.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-ControllerSolution.o -MD -MP -MF $(DEPDIR)/App-ControllerSolution.Tpo -c -o App-ControllerSolution.o `test -f 'Application/ControllerSolution.cpp' || echo '$(srcdir)/'`Application/ControllerSolution.cpp
	$(am__mv) $(DEPDIR)/App-ControllerSolution.Tpo $(DEPDIR)/App-ControllerSolution.Po
#	source='Application/ControllerSolution.cpp' object='App-ControllerSolution.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-ControllerSolution.o `test -f 'Application/ControllerSolution.cpp' || echo '$(srcdir)/'`Application/ControllerSolution.cpp

App-ControllerSolution.obj: Application/ControllerSolution.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-ControllerSolution.obj -MD -MP -MF $(DEPDIR)/App-ControllerSolution.Tpo -c -o App-ControllerSolution.obj `if test -f 'Application/ControllerSolution.cpp'; then $(CYGPATH_W) 'Application/ControllerSolution.cpp'; else $(CYGPATH_W) '$(srcdir)/Application/ControllerSolution.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-ControllerSolution.Tpo $(DEPDIR)/App-ControllerSolution.Po
#	source='Application/ControllerSolution.cpp' object='App-ControllerSolution.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-ControllerSolution.obj `if test -f 'Application/ControllerSolution.cpp'; then $(CYGPATH_W) 'Application/ControllerSolution.cpp'; else $(CYGPATH_W) '$(srcdir)/Application/ControllerSolution.cpp'; fi`

App-HelperOrderResultByWeight.o: Application/HelperOrderResultByWeight.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-HelperOrderResultByWeight.o -MD -MP -MF $(DEPDIR)/App-HelperOrderResultByWeight.Tpo -c -o App-HelperOrderResultByWeight.o `test -f 'Application/HelperOrderResultByWeight.cpp' || echo '$(srcdir)/'`Application/HelperOrderResultByWeight.cpp
	$(am__mv) $(DEPDIR)/App-HelperOrderResultByWeight.Tpo $(DEPDIR)/App-HelperOrderResultByWeight.Po
#	source='Application/HelperOrderResultByWeight.cpp' object='App-HelperOrderResultByWeight.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-HelperOrderResultByWeight.o `test -f 'Application/HelperOrderResultByWeight.cpp' || echo '$(srcdir)/'`Application/HelperOrderResultByWeight.cpp

App-HelperOrderResultByWeight.obj: Application/HelperOrderResultByWeight.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -MT App-HelperOrderResultByWeight.obj -MD -MP -MF $(DEPDIR)/App-HelperOrderResultByWeight.Tpo -c -o App-HelperOrderResultByWeight.obj `if test -f 'Application/HelperOrderResultByWeight.cpp'; then $(CYGPATH_W) 'Application/HelperOrderResultByWeight.cpp'; else $(CYGPATH_W) '$(srcdir)/Application/HelperOrderResultByWeight.cpp'; fi`
	$(am__mv) $(DEPDIR)/App-HelperOrderResultByWeight.Tpo $(DEPDIR)/App-HelperOrderResultByWeight.Po
#	source='Application/HelperOrderResultByWeight.cpp' object='App-HelperOrderResultByWeight.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(App_CPPFLAGS) $(CPPFLAGS) $(App_CXXFLAGS) $(CXXFLAGS) -c -o App-HelperOrderResultByWeight.obj `if test -f 'Application/HelperOrderResultByWeight.cpp'; then $(CYGPATH_W) 'Application/HelperOrderResultByWeight.cpp'; else $(CYGPATH_W) '$(srcdir)/Application/HelperOrderResultByWeight.cpp'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod u+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) $(HEADERS) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-libtool mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic clean-libtool ctags dist \
	dist-all dist-bzip2 dist-gzip dist-lzip dist-lzma dist-shar \
	dist-tarZ dist-xz dist-zip distcheck distclean \
	distclean-compile distclean-generic distclean-hdr \
	distclean-libtool distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-binPROGRAMS


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
